name: flood-impacts
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.23.0
  - contextily=1.6.2
  - earthengine-api=1.5.19
  - exactextract=0.2.1
  - geopandas=1.0.1
  - geos=3.13.0
  - matplotlib=3.9.4
  - netcdf4=1.7.2
  - numpy=2.0.2
  - pandas=2.2.3
  - proj=9.5.1
  - pyproj=3.6.1
  - python=3.10.1
  - rasterio=1.4.3
  - rioxarray=0.15.0
  - seaborn=0.13.2
  - scipy=1.13.1
  - shapely=2.0.6
  - xarray=2024.7.0
